Work around dubious new TypeScript errors.
lib/types.ts:411:5 - error TS2590: Expression produces a union type that
is too complex to represent.

411     builtInTypes[name] = type;
        ~~~~~~~~~~~~~~~~~~

lib/types.ts:413:35 - error TS2339: Property 'constructor' does not exist
on type 'T'.

413     if (example && typeof example.constructor === "function") {
                                      ~~~~~~~~~~~