Bump @types/node from 12.0.0 to 16.11.10 (#657)
* Bump @types/node from 12.0.0 to 16.11.10

Bumps [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node) from 12.0.0 to 16.11.10.
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node)

* Adjust assertion type narrowing to avoid TS error:

  test/ecmascript.ts(235,10): error TS2339: Property 'declarations' does not exist on type 'never'

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ben Newman <ben@benjamn.com>