Work around dubious new TypeScript errors.
lib/types.ts:413:35 - error TS2339: Property 'constructor' does not exist
on type 'T'.

413     if (example && typeof example.constructor === "function") {
                                      ~~~~~~~~~~~

lib/types.ts:414:35 - error TS2339: Property 'constructor' does not exist
on type 'T'.

414       builtInCtorFns.push(example.constructor);
                                      ~~~~~~~~~~~